title: "Shourov Joader"
header_pages:
  - index.md
  - cv.md
  - research.md
description: "Undergraduate Student at BUET"
baseurl: "" # leave empty for GitHub Pages
url: "https://jdickamazz.github.io"
theme: theme-jekyll-minimal
